# Generated by Django 3.1.6 on 2021-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210413_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_subdomain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
