# Generated by Django 3.1.6 on 2021-04-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_restaurant_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant_subdomain',
        ),
    ]
