# Generated by Django 2.0.6 on 2018-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_orderitem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=70)),
                ('note_body', models.TextField()),
                ('nodte_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
