# Generated by Django 2.0.6 on 2018-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_sitenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenote',
            name='nodte_date',
            field=models.DateField(),
        ),
    ]
