# Generated by Django 3.1.6 on 2021-05-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20210503_0144'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My site', max_length=100)),
                ('message', models.TextField()),
                ('base_color', models.CharField(max_length=20)),
                ('text_color', models.CharField(max_length=20)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='application/% Y/% m/% d/')),
                ('restaurant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branding', to='restaurant.restaurant')),
            ],
        ),
    ]
