# Generated by Django 3.1.6 on 2021-03-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210330_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='next_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlet',
            name='same_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlet',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
