# Generated by Django 3.1.6 on 2021-04-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('restaurant', '0004_auto_20210409_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.baseentity')),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=400)),
                ('is_published', models.BooleanField(default=False)),
            ],
            bases=('base.baseentity',),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('ITEM', 'Item'), ('MODIFIER', 'Modifier')], default='Item', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.baseentity')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('modifier_type', models.CharField(choices=[('SINGLE', 'Single'), ('Multiple', 'MULTIPLE')], max_length=10)),
                ('items', models.ManyToManyField(blank=True, related_name='modifier', to='restaurant.Inventory')),
            ],
            bases=('base.baseentity',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('items', models.ManyToManyField(blank=True, related_name='category', to='restaurant.Inventory')),
                ('menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='restaurant.menus')),
            ],
        ),
    ]
