# Generated by Django 3.1.6 on 2021-04-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210410_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_menu', to='restaurant.outlet'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_modifier', to='restaurant.outlet'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('ITEM', 'Item'), ('MODIFIER', 'Modifier')], default='ITEM', max_length=10),
        ),
        migrations.AlterField(
            model_name='menus',
            name='platform',
            field=models.CharField(choices=[('ONNO', 'Onno')], default='ONNO', max_length=10),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='modifier_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('Multiple', 'MULTIPLE')], default='SINGLE', max_length=10),
        ),
    ]
