# Generated by Django 3.1.6 on 2021-04-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210411_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(default=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pause_order', to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='LiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed', models.BooleanField(default=True)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('rider_confirmed', models.BooleanField(default=False)),
                ('preparing', models.BooleanField(default=False)),
                ('waiting', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_order', to='restaurant.order')),
            ],
        ),
    ]
