# Generated by Django 3.1.6 on 2021-04-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_liveorder_pauseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
