# Generated by Django 3.1.6 on 2021-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pauseorder',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER_PLACED', 'ORDER_PLACED'), ('CUSTOMER_CONFIRMED', 'CUSTOMER_CONFIRMED'), ('RIDER_CONFIRMED', 'RIDER_CONFIRMED'), ('PREPARING', 'PREPARING'), ('WAITING', 'WAITING'), ('DISPATCHED', 'DISPATCHED')], default='ORDER_PLACED', max_length=31),
        ),
        migrations.DeleteModel(
            name='LiveOrder',
        ),
        migrations.DeleteModel(
            name='PauseOrder',
        ),
    ]
