# Generated by Django 3.1.6 on 2021-05-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20210502_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_PLACED', 'Order Placed'), ('CUSTOMER_CONFIRMED', 'Customer Confirmed'), ('RIDER_CONFIRMED', 'Rider Confirmed'), ('PREPARING', 'Preparing'), ('WAITING', 'Waitting'), ('DISPATCHED', 'Dispatched'), ('DELIVERY', 'Delivery'), ('ORDER_CANCELLED', 'Order Cancelled')], default='ORDER_CREATED', max_length=31),
        ),
    ]
