# Generated by Django 3.1.6 on 2021-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20210503_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
