# Generated by Django 2.0.6 on 2018-07-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_title', models.CharField(max_length=22)),
                ('box_body', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category_image', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dalivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalivery', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_model', models.CharField(blank=True, max_length=40, null=True)),
                ('product_serials', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('product_image', models.CharField(max_length=120)),
                ('gallery_image1', models.CharField(blank=True, max_length=120, null=True)),
                ('gallery_image2', models.CharField(blank=True, max_length=120, null=True)),
                ('gallery_image3', models.CharField(blank=True, max_length=120, null=True)),
                ('gallery_image4', models.CharField(blank=True, max_length=120, null=True)),
                ('gallery_image5', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at_item', models.DateField(auto_now=True)),
                ('avaiableable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Availability')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Category')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Color')),
                ('product_dalivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Dalivery')),
            ],
        ),
        migrations.CreateModel(
            name='SectionAds1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SectionAds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_title', models.CharField(blank=True, max_length=30, null=True)),
                ('ads_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_layer1', models.CharField(max_length=15)),
                ('slide_layer2', models.CharField(max_length=25)),
                ('slide_layer3', models.CharField(max_length=35)),
                ('slide_link', models.CharField(max_length=20)),
                ('slider_image', models.ImageField(upload_to='slider')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_warranty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Warranty'),
        ),
    ]
