# Generated by Django 2.0.6 on 2018-07-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20180710_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
