# Generated by Django 2.0.6 on 2018-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20180711_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slide_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.CharField(max_length=200),
        ),
    ]
