# Generated by Django 2.0.6 on 2018-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20180713_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
