# Generated by Django 2.0.6 on 2018-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_homepageads'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
